services:
  go:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/sidemenulab?sslmode=disable
    networks:
      - app-network
  postgres:
    image: postgres:15
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: sidemenulab
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  db-vol:

networks:
  app-network:
    driver: bridge
